package models;

//Generated by Liubisheng
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Entity;
import javax.persistence.Table;

import play.data.validation.MaxSize;
import play.data.validation.Required;
import play.db.jpa.Model;

@Entity
@Table(name="setting")
public class Setting extends Model {

    @Required
    @MaxSize(200)
    public String name;
    @MaxSize(500)
    public String value;
    @MaxSize(500)
    public String extvalue;
    @MaxSize(1000)
    public String description;

    //default constructor 
    public Setting() {
    }
    public Setting(long id) {
     	this.id = id;
    }
    public Setting(long id, String name) {
        this.id = id;
        this.name = name;
    }
    
    public static String value(String name,String defaultvalue){
    	Setting s = Setting.find("name=?", name).first();
    	if(s != null){
    		return s.value;
    	}else{
    		return defaultvalue;
    	}
    }
    
    public static String value(String name){
    	Setting s = Setting.find("name=?", name).first();
    	if(s != null){
    		return s.value;
    	}else{
    		return null;
    	}
    }
    
    public static List<String> values(String name){
    	List<Setting> setings = Setting.find("name=?", name).fetch();
    	List<String> svlist = new ArrayList();
    	for(Setting s: setings){
    		svlist.add(s.value);
    	}
    	return svlist;
    }

    public static Map<String,String> extvalues(String name){
    	List<Setting> setings = Setting.find("name=?", name).fetch();
    	Map<String,String> svvmap = new HashMap();
    	for(Setting s: setings){
    		svvmap.put(s.value, s.extvalue);
    	}
    	return svvmap;
    }     


}


